// Code generated by "stringer -type ExitType object.go"; DO NOT EDIT.

package evaluator

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RETURN-0]
	_ = x[BREAK-1]
	_ = x[CONTINUE-2]
}

const _ExitType_name = "RETURNBREAKCONTINUE"

var _ExitType_index = [...]uint8{0, 6, 11, 19}

func (i ExitType) String() string {
	if i < 0 || i >= ExitType(len(_ExitType_index)-1) {
		return "ExitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExitType_name[_ExitType_index[i]:_ExitType_index[i+1]]
}
